/**
 * User service — all direct database access for the users table.
 * Controllers must never query the database directly; they call this module.
 */

import { pool } from "../db/index";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CreateUserInput {
  full_name: string;
  email: string | null;
  mobile: string | null;
  password_hash: string;
  country?: string | null;
}

export interface UserRow {
  id: string;
  player_id: string;
  full_name: string;
  email: string | null;
  mobile: string | null;
  country: string | null;
  avatar: string | null;
  is_verified: boolean;
  status: string;
  last_login_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/**
 * Find a user by their email address (case-insensitive).
 * Returns null when no match is found.
 */
export async function findByEmail(email: string): Promise<UserRow | null> {
  if (!pool) return null;
  const { rows } = await pool.query<UserRow>(
    "SELECT * FROM users WHERE lower(email) = lower($1) LIMIT 1",
    [email],
  );
  return rows[0] ?? null;
}

/**
 * Find a user by their mobile number.
 * Returns null when no match is found.
 */
export async function findByMobile(mobile: string): Promise<UserRow | null> {
  if (!pool) return null;
  const { rows } = await pool.query<UserRow>(
    "SELECT * FROM users WHERE mobile = $1 LIMIT 1",
    [mobile],
  );
  return rows[0] ?? null;
}

/**
 * Insert a new user row.
 * `player_id` is auto-generated by the database trigger when not supplied.
 * Returns the newly created row (without password_hash).
 */
export async function createUser(
  input: CreateUserInput,
): Promise<Pick<UserRow, "id" | "player_id" | "full_name" | "email" | "mobile" | "status" | "created_at">> {
  if (!pool) {
    throw new Error("Database is not available.");
  }

  const { rows } = await pool.query<Pick<UserRow, "id" | "player_id" | "full_name" | "email" | "mobile" | "status" | "created_at">>(
    `INSERT INTO users (full_name, email, mobile, password_hash, country)
     VALUES ($1, $2, $3, $4, $5)
     RETURNING id, player_id, full_name, email, mobile, status, created_at`,
    [
      input.full_name,
      input.email ?? null,
      input.mobile ?? null,
      input.password_hash,
      input.country ?? null,
    ],
  );

  return rows[0]!;
}
